### ISSUE TITLE
Issue running figaro with 16S V4 data

### ISSUE THREAD

**Issue by pig-raffles** [Zymo-Research/figaro#35]
Hi, 

I am running Figaro via docker. The runs start ok but keep finishing with an error message:

Traceback (most recent call last):
  File "/opt/figaro/figaro/figaro.py", line 218, in <module>
    main()
  File "/opt/figaro/figaro/figaro.py", line 210, in main
    resultTable, forwardCurve, reverseCurve = trimParameterPrediction.performAnalysisLite(parameters.inputDirectory.value, parameters.minimumCombinedReadLength.value, subsample =  parameters.subsample.value, percentile = parameters.percentile.value, forwardPrimerLength=parameters.forwardPrimerLength.value, reversePrimerLength=parameters.reversePrimerLength.value, namingStandardAlias=fileNamingStandard)
  File "/opt/figaro/figaro/trimParameterPrediction.py", line 457, in performAnalysisLite
    resultTable = runTrimParameterTestLite(forwardExpectedErrorMatrix, reverseExpectedErrorMatrix, trimPositions, minimumTrimmingPositions, forwardCurve, reverseCurve, forwardPrimerLength, reversePrimerLength)
  File "/opt/figaro/figaro/trimParameterPrediction.py", line 347, in runTrimParameterTestLite
    reverseExpectedErrors = reverseExpectedErrorMatrix[reverseTrimPosition - reverseMinimumTrimPosition]
IndexError: index 327 is out of bounds for axis 0 with size 27

Any idea what the problem could be. Could it be a memory issue?

**Comment by michael-weinstein** [comment]
I would have see what your run parameters are as well as your reads.  My first guess would be that you might have some very short reads in your sample.  Can you check that all your reads are of uniform length in the fastq (especially the paired-end 2 reads)?

**Comment by pig-raffles** [comment]
Hi,

Run parameters:

docker container run --rm -e AMPLICONLENGTH=254 -e FORWARDPRIMERLENGTH=0 -e REVERSEPRIMERLENGTH=0 -e MINIMUMOVERLAP=20

FastQC gives no indication that there are very short reads, just stating that R1 and R2 read files contain reads of 301 bp

**Comment by michael-weinstein** [comment]
Are the lengths of the reads longer than your intended amplicon?  If so, check out https://github.com/Zymo-Research/figaro/issues/36

**Comment by pig-raffles** [comment]
If this is the case, would this program still be appropriate for using with 16S V4 paired reads? I am just wondering whether this would introduce biases into the trimming optimisation results

**Comment by michael-weinstein** [comment]
Should still be OK.  The program is just optimizing the trimming sites.  The only issue I can foresee here is that you will have much less overlap in the middle, since the program will trim to a pre-determined overlap length (default of 20).  I can’t imagine how this would cause any major bias unless there’s already something seriously wrong with the reads.
