### ISSUE TITLE
Could not infer read orientation from filename

### ISSUE THREAD

**Issue by ekgough** [Zymo-Research/figaro#48]
HI I get the following output when I run this command to apply figaro to my cutadapt pimer-removed fastq giles.

python3 ~/figaro/figaro/figaro.py  -o quality.limits/figaro_out -a 300 -f 19 -r 20

Traceback (most recent call last):
  File "/home/ethan/figaro/figaro/figaro.py", line 218, in <module>
    main()
  File "/home/ethan/figaro/figaro/figaro.py", line 208, in main
    parameters = getApplicationParameters()
  File "/home/ethan/figaro/figaro/figaro.py", line 17, in getApplicationParameters
    return getApplicationParametersFromCommandLine()
  File "/home/ethan/figaro/figaro/figaro.py", line 89, in getApplicationParametersFromCommandLine
    totalFileSize = fastqAnalysis.getEstimatedFastqSizeSumFromDirectory(inputDirectory, fileNamingStandard)
  File "/home/ethan/figaro/figaro/fastqAnalysis.py", line 120, in getEstimatedFastqSizeSumFromDirectory
    fastqList = fastqHandler.findSamplesInFolder(path, fileNamingStandard)
  File "/home/ethan/figaro/figaro/fastqHandler.py", line 538, in findSamplesInFolder
    fastqFileInfoList.append(namingStandard(filePath))
  File "/home/ethan/figaro/figaro/fileNamingStandards.py", line 18, in __init__
    self.group, self.sampleNumber, self.direction = self.getSampleInfo(self.fileName)
  File "/home/ethan/figaro/figaro/fileNamingStandards.py", line 61, in getSampleInfo
    raise ValueError("Could not infer read orientation from filename: {}".format(fileName))
**ValueError: Could not infer read orientation from filename: 1001_C_1_S39_L001_R1_001.trimmed.fastq.gz**

I'm not sure why figaro is unable to infer the read orientation from 1001_C_1_S39_L001_R1_001.trimmed.fastq.gz, which is the first file in my directory. 
Thank you.
Best wishes
Ethan

**Comment by ekgough** [comment]
Ok So it seems I was able to resolve this issue by renaming my fastq files to fit the Illumina naming convention for fastq files. however, now I have a different problem that I will post in a different thread.
best wishes

**Comment by gailenriquez** [comment]
how did you fix the above issue? I named my files the same way and I get the same 
error "Could not infer read orientation"

**Comment by gailenriquez** [comment]
Hi sorry for the late response. My filename looks like this: MB002B_S157_L001_R1_001.fastq.gz and MB002B_S157_L001_R2_001.fastq.gz
________________________________

**Comment by carordc** [comment]
Hello,
I am having the same issue. My files are Illumina sequencing with the following name Bioreactor_1_S88_L001_R1_001.fastq

Thanks!

**Comment by ekgough** [comment]
I'm sorry I did not get a response to my query and I was not able to
resolve the issue I was having.

**Comment by carordc** [comment]
Thank you for answering me @ekgough.

@cschu is that a solution for it?

**Comment by cschu** [comment]
@carordc Try renaming the files, removing the `_001` after the `_R1` or `_R2` part. You could also try a different file naming standard with `-F <filenamingstandard>`, but I'm not sure whether your format is covered. I think the `_` in `Bioreactor_1` may cause a problem for the `illumina` naming standard.

**Comment by carordc** [comment]
> @carordc Try renaming the files, removing the `_001` after the `_R1` or `_R2` part. You could also try a different file naming standard with `-F <filenamingstandard>`, but I'm not sure whether your format is covered. I think the `_` in `Bioreactor_1` may cause a problem for the `illumina` naming standard.

Thanks! I took out the _001 and the beggining, and it worked. :)

**Comment by cschu** [comment]
Glad it worked!
