### ISSUE TITLE
Unable to validate fastq files enough to perform this operation

### ISSUE THREAD

**Issue by ekgough** [Zymo-Research/figaro#49]
Hi 
When I run figaro from the command line I get the following output.

Traceback (most recent call last):
  File "/home/ethan/figaro/figaro/figaro.py", line 218, in <module>
    main()
  File "/home/ethan/figaro/figaro/figaro.py", line 210, in main
    resultTable, forwardCurve, reverseCurve = trimParameterPrediction.performAnalysisLite(parameters.inputDirectory.value, parameters.minimumCombinedReadLength.value, subsample =  parameters.subsample.value, percentile = parameters.percentile.value, forwardPrimerLength=parameters.forwardPrimerLength.value, reversePrimerLength=parameters.reversePrimerLength.value, namingStandardAlias=fileNamingStandard)
  File "/home/ethan/figaro/figaro/trimParameterPrediction.py", line 448, in performAnalysisLite
    forwardReadLength, reverseReadLength = checkReadLengths(fastqList)
  File "/home/ethan/figaro/figaro/trimParameterPrediction.py", line 407, in checkReadLengths
    raise fastqHandler.FastqValidationError("Unable to validate fastq files enough to perform this operation. Please check log for specific error(s).")
**fastqHandler.FastqValidationError: Unable to validate fastq files enough to perform this operation. Please check log for specific error(s).**

What can be done to deal with the Unable to validate fastq files enough to perform this operation error. My log is empty.

**Comment by Marenno** [comment]
Hi i have the same issue. Has anyone resolved this already?
Thanks in advance.
Cheers,
Maren

**Comment by Marenno** [comment]
Okay, sorry i fixed this problem. My input files didn't contain the primer sequences  anymore. However, now i'm getting an index Error...
