### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable'`

### ISSUE THREAD

**Issue by msubirana** [Zymo-Research/figaro#50]
Hi, I upload to ubuntu 22.04 and now I getting this error in my pipe, any suggestions?

`Traceback (most recent call last):
  File "/home/msg/Documents/phylgut/microbiome/repos/figaro/figaro/figaro.py", line 4, in <module>
    from . import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msg/Documents/phylgut/microbiome/repos/figaro/figaro/trimParameterPrediction.py", line 4, in <module>
    from . import fileNamingStandards
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msg/Documents/phylgut/microbiome/repos/figaro/figaro/figaro.py", line 6, in <module>
    import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
  File "/home/msg/Documents/phylgut/microbiome/repos/figaro/figaro/trimParameterPrediction.py", line 9, in <module>
    import fileNamingStandards, fastqHandler, fastqAnalysis, expectedErrorCurve
  File "/home/msg/Documents/phylgut/microbiome/repos/figaro/figaro/expectedErrorCurve.py", line 13, in <module>
    class ExponentialFit(object):
  File "/home/msg/Documents/phylgut/microbiome/repos/figaro/figaro/expectedErrorCurve.py", line 17, in ExponentialFit
    def __init__(self, a:float, b:float, c:float, covariance:collections.Iterable = None, rSquared:float = None, curvePNG:str=None):
AttributeError: module 'collections' has no attribute 'Iterable'`

**Comment by michael-weinstein** [comment]
You are running on a newer version of python than is supported here.  The collections.iterable was deprecated and removed I think at 3.9 (not 100% sure on that).  Try running on 3.7 and see how it goes.

Also, sorry for being absent on here, I am not with Zymo anymore and my checking with their microbiome director to find out about the future of support for Figaro with them has gone unanswered.  If I don't hear back soon, I will most likely fork Figaro over to my own personal repo.  I have already made some improvements to it that leverage newer Python version features.

**Comment by msubirana** [comment]
Hi! Do you have any news about Figaro?
