### ISSUE TITLE
ImportError during Figaro running

### ISSUE THREAD

**Issue by l-gallucci** [Zymo-Research/figaro#60]
Hi all, 

I'm trying to run figaro on a subset of samples. I'm facing this problems after running it with the following command set:

`python3 figaro.py -i /Users/lgallucc/Desktop/Tempor/Luigi/ -o /Users/lgallucc/Desktop/TemporLuigi/Figaro -a 320 -f 20 -r 20`
```
Traceback (most recent call last):
  File "/Users/lgallucc/figaro/figaro/figaro.py", line 4, in <module>
    from . import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lgallucc/figaro/figaro/trimParameterPrediction.py", line 4, in <module>
    from . import fileNamingStandards
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lgallucc/figaro/figaro/figaro.py", line 6, in <module>
    import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
  File "/Users/lgallucc/figaro/figaro/trimParameterPrediction.py", line 9, in <module>
    import fileNamingStandards, fastqHandler, fastqAnalysis, expectedErrorCurve
  File "/Users/lgallucc/figaro/figaro/expectedErrorCurve.py", line 13, in <module>
    class ExponentialFit(object):
  File "/Users/lgallucc/figaro/figaro/expectedErrorCurve.py", line 17, in ExponentialFit
    def __init__(self, a:float, b:float, c:float, covariance:collections.Iterable = None, rSquared:float = None, curvePNG:str=None):
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by bark9299** [comment]
I am getting the same error:

    from . import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elysebarker/test_figaro/figaro.py", line 6, in <module>
    import environmentParameterParser, fileNamingStandards, fastqAnalysis, trimParameterPrediction
ModuleNotFoundError: No module named 'environmentParameterParser'

**Comment by nvpatin** [comment]
I am getting the same error, running Figaro on Mac OS 13.4.1 and Python 3.10.

**Comment by hjarnek** [comment]
This is because since Python 3.3 the `collections` module [has been succeeded](https://docs.python.org/3/library/collections.abc.html) by the `collections.abc` module. You can fix this by simply find&replace all instances of "collections" with "collections.abc" in all Figaro Python scripts that contain this module.

Figaro is not maintained anymore though. There has been some rumours about an update called Figaro2 for a long time, but not from Zymo.

**Comment by ayoraind** [comment]
Thank you very much @hjarnek. Your suggestion bailed me out today. It worked!

**Comment by handibles** [comment]
for future timetravellers, this issue was addressed in #63 and proposed in #68 - hopefully should work as intended now.
